### ISSUE TITLE
Unable to reproduce doc example

### ISSUE THREAD

**Issue by TorkelE** [DanielVandH/ProfileLikelihood.jl#89] opened 2023-12-05 00:06 UTC
Hello,

I am trying to reproduce this example from the docs: https://danielvandh.github.io/ProfileLikelihood.jl/dev/logistic/

However, this line: `@time sol = mle(prob, NLopt.LD_LBFGS)` failed:
```
julia> @time sol = mle(prob, NLopt.LD_LBFGS)
┌ Warning: NLopt failed to converge: FORCED_STOP
└ @ OptimizationNLopt ~/.julia/packages/OptimizationNLopt/CgKow/src/OptimizationNLopt.jl:181
  0.002261 seconds (217 allocations: 17.359 KiB)
LikelihoodSolution. retcode: Failure
Maximum likelihood: -0.0
Maximum likelihood estimates: 3-element Vector{Float64}
     λ: 0.01
     K: 100.0
     u₀: 10.0
```

Here is the full code:
```julia
using Random 
using ProfileLikelihood
using Optimization 
using OrdinaryDiffEq
using CairoMakie 
using LaTeXStrings
using OptimizationNLopt
using Test
using StableRNGs

using OrdinaryDiffEq, Random, StableRNGs
λ = 0.01
K = 100.0
u₀ = 10.0
t = 0:100:1000
σ = 10.0
@inline function ode_fnc(u, p, t)
    λ, K = p
    du = λ * u * (1 - u / K)
    return du
end
# Initial data is obtained by solving the ODE 
tspan = extrema(t)
p = (λ, K)
prob = ODEProblem(ode_fnc, u₀, tspan, p)
sol = solve(prob, Rosenbrock23(), saveat=t)
rng = StableRNG(123)
uᵒ = sol.u + σ * randn(rng, length(t))

function loglik_fnc2(θ, data, integrator)
    λ, K, u₀ = θ
    uᵒ, σ = data
    integrator.p[1] = λ
    integrator.p[2] = K
    reinit!(integrator, u₀)
    solve!(integrator)
    return gaussian_loglikelihood(uᵒ, integrator.sol.u, σ, length(uᵒ))
end

lb = [0.0, 50.0, 0.0] # λ, K, u₀
ub = [0.05, 150.0, 50.0]
θ₀ = [λ, K, u₀]
syms = [:λ, :K, :u₀]
prob = LikelihoodProblem(
    loglik_fnc2, θ₀, ode_fnc, u₀, maximum(t); # Note that u₀ is just a placeholder IC in this case since we are estimating it
    syms=syms,
    data=(uᵒ, σ),
    ode_parameters=[1.0, 1.0], # temp values for [λ, K]
    ode_kwargs=(verbose=false, saveat=t),
    prob_kwargs=(lb=lb, ub=ub),
    ode_alg=Rosenbrock23()
)

using OptimizationNLopt
@time sol = mle(prob, NLopt.LD_LBFGS)
```

and here is the environment:
```
⌃ [13f3f980] CairoMakie v0.11.1
  [479239e8] Catalyst v13.5.1
  [a93c6f00] DataFrames v1.6.1
⌃ [0c46a032] DifferentialEquations v7.10.0
  [31c24e10] Distributions v0.25.103
  [b964fa9f] LaTeXStrings v1.3.1
  [429524aa] Optim v1.7.8
  [7f7a1694] Optimization v3.19.3
  [4e6fcdb7] OptimizationNLopt v0.1.8
⌃ [1dea7af3] OrdinaryDiffEq v6.58.2
⌃ [48d54b35] PEtab v2.0.0
  [91a5bcdd] Plots v1.39.0
  [3fca794e] ProfileLikelihood v0.3.2
  [860ef19b] StableRNGs v1.0.0
```
(on Julia 1.10)

Am I making some misstake here?

**Comment by DanielVandH** [comment] 2023-12-05 00:55
Hm. I'll have to look into this a bit further a bit later to try and understand what's happening, but it seems to be somehow related to the autodiff. If I change to an Optim alg so that the error shows:

```julia
using OptimizationOptimJL
@time sol = mle(prob, Optim.LBFGS())

ERROR: MethodError: objects of type Nothing are not callable
Stacktrace:
  [1] (::OptimizationOptimJL.var"#19#23"{…})(G::Vector{…}, θ::Vector{…})
    @ OptimizationOptimJL C:\Users\User\.julia\packages\OptimizationOptimJL\r5j6D\src\OptimizationOptimJL.jl:273
  [2] value_gradient!!(obj::OnceDifferentiable{Float64, Vector{Float64}, Vector{Float64}}, x::Vector{Float64})
    @ NLSolversBase C:\Users\User\.julia\packages\NLSolversBase\kavn7\src\interface.jl:82
  [3] value_gradient!!(bw::Optim.BarrierWrapper{…}, x::Vector{…})
    @ Optim C:\Users\User\.julia\packages\Optim\V8ZEC\src\multivariate\solvers\constrained\fminbox.jl:81
  [4] initial_state(method::LBFGS{…}, options::Optim.Options{…}, d::Optim.BarrierWrapper{…}, initial_x::Vector{…})
    @ Optim C:\Users\User\.julia\packages\Optim\V8ZEC\src\multivariate\solvers\first_order\l_bfgs.jl:164
  [5] optimize(df::OnceDifferentiable{…}, l::Vector{…}, u::Vector{…}, initial_x::Vector{…}, F::Fminbox{…}, options::Optim.Options{…})
    @ Optim C:\Users\User\.julia\packages\Optim\V8ZEC\src\multivariate\solvers\constrained\fminbox.jl:322
  [6] __solve(cache::OptimizationCache{…})
    @ OptimizationOptimJL C:\Users\User\.julia\packages\OptimizationOptimJL\r5j6D\src\OptimizationOptimJL.jl:297
  [7] solve!
    @ C:\Users\User\.julia\packages\SciMLBase\szsYq\src\solve.jl:162 [inlined]
  [8] solve(prob::OptimizationProblem, alg::Any, args::Vararg{Any}; kwargs...)
    @ SciMLBase C:\Users\User\.julia\packages\SciMLBase\szsYq\src\solve.jl:83 [inlined]
  [9] solve(::OptimizationProblem{…}, ::Rosenbrock23{…})
    @ SciMLBase C:\Users\User\.julia\packages\SciMLBase\szsYq\src\solve.jl:80 [inlined]
 [10] mle(::LikelihoodProblem{…}, ::LBFGS{…}; kwargs::@Kwargs{})
    @ ProfileLikelihood C:\Users\User\.julia\dev\ProfileLikelihood\src\mle.jl:15
 [11] mle(::LikelihoodProblem{…}, ::LBFGS{…})
    @ ProfileLikelihood C:\Users\User\.julia\dev\ProfileLikelihood\src\mle.jl:13
 [12] macro expansion
    @ .\timing.jl:279 [inlined]
 [13] top-level scope
    @ .\Untitled-1:58
Some type information was truncated. Use `show(err)` to see complete types.
```

Using finite differences fixes it:

```julia
prob = LikelihoodProblem(
    loglik_fnc2, θ₀, ode_fnc, u₀, maximum(t); # Note that u₀ is just a placeholder IC in this case since we are estimating it
    syms=syms,
    data=(uᵒ, σ),
    ode_parameters=[1.0, 1.0], # temp values for [λ, K]
    ode_kwargs=(verbose=false, saveat=t),
    prob_kwargs=(lb=lb, ub=ub),
    f_kwargs=(adtype=AutoFiniteDiff(),),
    ode_alg=Rosenbrock23()
)

using OptimizationNLopt
@time sol = mle(prob, NLopt.LD_LBFGS)

  0.243547 seconds (637.11 k allocations: 27.297 MiB, 13.46% gc time, 96.04% compilation time: 96% of which was recompilation)
LikelihoodSolution. retcode: Success
Maximum likelihood: -37.85651536671429
Maximum likelihood estimates: 3-element Vector{Float64}
     λ: 0.011490557348931936
     K: 92.91712071621922
     u₀: 7.319670187817508
```

Maybe it's an Optimization.jl issue?

**Comment by TorkelE** [comment] 2023-12-05 00:57
Hmm, maybe! I will try this as well (maybe it is related to https://github.com/DanielVandH/ProfileLikelihood.jl/issues/90?).

Thansk for the quick reply!

**Comment by DanielVandH** [comment] 2023-12-05 02:43
This was somehow already fixed in the tests but not in the docs - my mistake. #92 will put the fix into the docs so that they are reproducible. It's still not clear to me why `objects of type Nothing are not callable` happens, but I'll close this once #92 is merged since I'm not sure it's a problem of this package.

**Comment by TorkelE** [comment] 2023-12-05 02:54
sounds good, thanks for looking into it so quickly!

**Closed** 2023-12-05 09:35 UTC
